# Generated by Django 2.2.5 on 2019-12-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Presenting_Complaint_Detail',
        ),
    ]
